# Generated by Django 2.2.13 on 2021-05-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('haiwei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgid_1', models.CharField(max_length=99)),
                ('imgid_2', models.CharField(max_length=99, null=True)),
                ('location', models.CharField(max_length=20)),
                ('wname', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('taste', models.CharField(max_length=999)),
                ('others', models.CharField(max_length=999, null=True)),
            ],
        ),
    ]
