# Generated by Django 2.2.13 on 2021-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiwei', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='imgid_1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='imgid_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
