# Generated by Django 2.2.13 on 2021-05-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiwei', '0003_auto_20210520_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='imgid_2',
        ),
        migrations.AlterField(
            model_name='food',
            name='imgid_1',
            field=models.ImageField(default='avatar.jpg', upload_to='photos'),
        ),
    ]
